#include "hash.h"
#include "config.h"
#include <string.h>
#include <stdio.h>

int main(void)
{
    const char *msg = "SSSSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely SSSSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely SSSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.SSpam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.Spam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.Spam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.Spam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.Spam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.Spam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.Spam, Spam, Spam, lovely Spam Wonderful Spam, Lovely Spam.Spam, Spam, Spam, lovely Spam.";
    unsigned char hash[HASH_LEN];
    for(int i = 0; i < 100000; ++i)
	    hash(msg,strlen(msg),hash);
}
