# This file was *autogenerated* from the file plot_perf_stats.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_10 = Integer(10); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
FNAME = "perf_stats.txt"

if __name__ == "__main__":
    f = open(FNAME,'r')
    lines = f.readlines()
    plist = [(log(int(l.split(':')[_sage_const_0 ],_sage_const_10 )),float(l.split(':')[_sage_const_1 ])) for l in lines]
    plot = list_plot(plist)
    plot.axes_labels(['$\log(bytelen(msg))$','$CPU cycles/byte$'])
    plot.set_legend_options(title="Cycles per bytes needed to hash a msg of x bytes")
    plot.save('plot_perf_stats.eps')
    plot.save('plot_perf_stats.png')
